name: Intra-verify

on:
  push:
#   schedule:
#     - cron: "5 20 * * *" # 日本時間の AM 5:05 (UTC 20:05) に実行

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # 5分でタイムアウトする
    strategy:
      matrix:
        node-version: [17.x]
    env:
      TOKYO_42_USERNAME: ${{ secrets.TOKYO_42_USERNAME }}
      TOKYO_42_PASSWORD: ${{ secrets.TOKYO_42_PASSWORD }}
      DISCORD_EMAIL: ${{ secrets.DISCORD_EMAIL }}
      DISCORD_PASSWORD: ${{ secrets.DISCORD_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: apt install
        run: apt-get update && apt-get install -y libgtk-3.0 libgbm-dev libnss3 libatk-bridge2.0-0 libasound2

      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: "17.x"

      - name: install command
        run: npm install -g yarn && yarn install

      - name: RUN main.js
        run: yarn dev
